### ISSUE TITLE
skywork天工模型MsLite推理提示找不到cstdint.h

### ISSUE THREAD

**Issue by gyy8426** [mindspore-lab/mindformers#9]
硬件 昇腾910B
驱动版本：23.0.rc3.b101
镜像版本：swr.cn-central-221.ovaijisuan.com/mindformers/mindformers0.8.0_mindspore2.2.0:aarch_20231025
按照教程说明将skywork模型转为CKPT然后转为mindir。
ckpt是能正常推理的，但是使用MSLite推理MindIR时报错，提示cstdint找不到。
具体报错信息如下：
/usr/local/Ascend/ascend-toolkit/7.0.RC1/aarch64-linux/tikcpp/tikcfw/impl/kernel_macros.h:7:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.

[ERROR] ME(16662,fffc696661e0,python):2023-12-20-14:57:12.448.382 [mindspore/lite/src/extendrt/delegate/ascend_ge/ge_graph_executor.cc:1176] operator()] RunAsync failed.
[ERROR] ME(16662,ffffbdf27ce0,python):2023-12-20-14:57:12.469.482 [mindspore/lite/src/extendrt/delegate/ascend_ge/ge_graph_executor.cc:1459] RunGraph] Exec compute graph failed, graph id 1
[ERROR] ME(16662,ffffbdf27ce0,python):2023-12-20-14:57:12.469.887 [mindspore/lite/src/extendrt/session/delegate_session.cc:245] RunGraph] GraphSinkSession::RunGraph run graph failed
[ERROR] ME(16662,ffffbdf27ce0,python):2023-12-20-14:57:12.469.954 [mindspore/lite/src/extendrt/cxx_api/model/model_impl.cc:640] Predict] ModelImpl::Predict RunGraph failed with Common error code.
Traceback (most recent call last):
  File "/home/gyy/projects/ASR/codes/mindformers-master/research/skywork/run_skywork_infer_lite.py", line 58, in <module>
    infer_main(args)
  File "/home/gyy/projects/ASR/codes/mindformers-master/research/skywork/run_skywork_infer_lite.py", line 43, in infer_main
    output = infer_model.infer(user_input, pad_token_id=0, input_seq_length=args.input_seq_length, eos_token_id=2)
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/mindformers/inference/infers/text_generator_infer.py", line 246, in infer
    output_ids = self.generate(input_ids, do_sample, top_k, top_p, temperature,
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/mindformers/inference/infers/text_generator_infer.py", line 380, in generate
    outputs = self._inc_infer(input_ids, current_index, valid_length, is_first_iteration, **kwargs)
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/mindformers/inference/infers/text_generator_infer.py", line 455, in _inc_infer
    outputs = self.full_model.predict(lite_inputs)
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/mindspore_lite/model.py", line 375, in predict
    return super(Model, self).predict(inputs_tensor, outputs)
  File "/root/miniconda3/envs/mindspore2.2_py39/lib/python3.9/site-packages/mindspore_lite/base_model.py", line 80, in predict
    raise RuntimeError(f"predict failed!")
RuntimeError: predict failed!

**Comment by Ash-Lee233** [comment]
您好，该代码仓为映射仓，可以去源码仓提问：https://gitee.com/mindspore/mindformers
